### ISSUE TITLE
Term Labels

### ISSUE THREAD

**Issue by dangalea** [PhIMaL/DeePyMoD_torch#10]
Hi,

I have come across your paper and code am interested in applying to a problem in atmospheric science. I have been trying to understand how the code works and would like to check whether there is a template for the output terms. For example, what would the terms given by `tensor([1, 2, 3, 4])` stand for?

Thanks.

**Comment by GJBoth** [comment]
Hi @dangalea,

The dictionary has a shape `[N_samples, N_terms]`. The indices you have above indicate the column index, which is dependent on your library. This however is and old library, the one you'd want to use is this one (and comes with documentation :-))
https://github.com/PhIMaL/DeePyMoD
